# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, please restart the server process.

include: ['_pages']

url: http://agile-france.org

collections:
  assemblee_generale:
    output: true
  bureau:
    output: true
  mot_conference:
    output: true

defaults:
  -
    scope:
      path: "" # means "all files"
    values:
      layout: default
  -
    scope:
      path: ""
      type: bureau # targets a collection
    values:
      layout: bureau
  -
    scope:
      path: ""
      type: mot_conference
    values:
      layout: mot_conference

plugins:
  - jekyll-postcss
  - jekyll-purgecss
