# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, please restart the server process.

include: ['_pages']

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
