# CircleCI 2.0 configuration file. See <https://circleci.com/docs/2.0/language-ruby/>.
version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.2

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "Gemfile" }}

      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          key: dependency-cache-{{ checksum "Gemfile" }}
          paths:
            - ./vendor/bundle

      - run:
          name: check Jekyll configuration
          command: bundle exec jekyll doctor

      - run:
          name: compile website
          command: bundle exec jekyll build --safe

      - run:
          name: check that Jekyll has compiled something
          command: test -s _site/index.html

      - run:
          name: start server
          command: bundle exec jekyll serve --no-watch --skip-initial-build
          background: true
      - run:
          name: wait for server to start
          command: |
            while ! curl --silent http://localhost:4000
            do sleep 1
            done
